# Without Parameters

In [1]:
import torch
from torch.nn import functional as F
from torch import nn

In [2]:
class CenteredLayer(nn.Module):
    def __init__(self) -> None:
        super().__init__()
    
    def forward(self, X):
        return X - X.mean()

In [3]:
layer = CenteredLayer()
layer(torch.FloatTensor([1, 2, 3, 4, 5]))

tensor([-2., -1.,  0.,  1.,  2.])

In [5]:
net = nn.Sequential(nn.Linear(8, 128), CenteredLayer())

In [6]:
Y = net(torch.rand(4, 8))
Y.mean()

tensor(-4.6566e-10, grad_fn=<MeanBackward0>)

# With Parameters

In [7]:
class MyLinear(nn.Module):
    def __init__(self, in_units, units) -> None:
        super().__init__()
        self.weight = nn.Parameter(torch.randn(size=(units, in_units), requires_grad=True))
        self.bias = nn.Parameter(torch.zeros((units,)))
    
    def forward(self, X):
        X = X @ self.weight.t() + self.bias
        return F.relu(X)

In [8]:
linear = MyLinear(5, 3)
linear.weight


Parameter containing:
tensor([[ 0.6577,  1.4714,  0.6389,  0.7967, -1.1480],
        [ 0.0274,  0.3814, -0.8470,  1.6986,  1.2310],
        [-0.3011, -1.7723,  2.7658, -2.4945, -0.5323]], requires_grad=True)

In [9]:
linear(torch.rand(2, 5))

tensor([[0.3305, 1.4074, 0.0000],
        [1.7340, 0.7638, 0.0000]], grad_fn=<ReluBackward0>)

In [10]:
net = nn.Sequential(MyLinear(64, 8), MyLinear(8, 1))
net(torch.rand(2, 64))

tensor([[8.3101],
        [4.6161]], grad_fn=<ReluBackward0>)