In [1]:
import torch

In [5]:
x = torch.arange(12)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [6]:
x.shape

torch.Size([12])

In [8]:
x.numel()

12

In [9]:
X = x.reshape(3,4)

In [10]:
X

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [11]:
torch.zeros((2,3,4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [15]:
x = torch.tensor([1.0,2,4,8])
y = torch.tensor([2,2,2,2])
y = torch.ones(4)
y = y * 2
x + y, x - y, x * y, x / y, x**y

(tensor([ 3.,  4.,  6., 10.]),
 tensor([-1.,  0.,  2.,  6.]),
 tensor([ 2.,  4.,  8., 16.]),
 tensor([0.5000, 1.0000, 2.0000, 4.0000]),
 tensor([ 1.,  4., 16., 64.]))

In [16]:
X = torch.arange(12, dtype=torch.float32).reshape((3,4))
Y = torch.tensor([[1.0, 2, 3, 4],[2, 1, 4, 3], [3, 2, 1, 4]])
torch.cat((X,Y),dim=0), torch.cat((X,Y),dim=1)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 1.,  2.,  3.,  4.],
         [ 2.,  1.,  4.,  3.],
         [ 3.,  2.,  1.,  4.]]),
 tensor([[ 0.,  1.,  2.,  3.,  1.,  2.,  3.,  4.],
         [ 4.,  5.,  6.,  7.,  2.,  1.,  4.,  3.],
         [ 8.,  9., 10., 11.,  3.,  2.,  1.,  4.]]))

In [17]:
X == Y

tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

In [18]:
Y == Y

tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

In [19]:
X.sum()

tensor(66.)

In [20]:
a = torch.arange(3).reshape([3,1])
b = torch.arange(2).reshape([1,2])
a, b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

In [21]:
a + b

tensor([[0, 1],
        [1, 2],
        [2, 3]])

In [22]:
X[-1]

tensor([ 8.,  9., 10., 11.])

In [23]:
X[1:3]

tensor([[ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [26]:
before = id(Y)
Y = Y + X
after = id(Y)
before == after

False

In [27]:
Z = torch.zeros_like(Y)
print('Z_id:',id(Z))
Z[:] = Y + X
print('Z_id:',id(Z))

Z_id: 130462253862480
Z_id: 130462253862480


In [28]:
before = id(Y)
Y += X
after = id(Y)
before == after

True

In [29]:
A = X.numpy()
B = torch.tensor(A)
type(A),type(B)

(numpy.ndarray, torch.Tensor)

In [31]:
a = torch.tensor([3.5])
a, a.item(), float(a), int(a)

(tensor([3.5000]), 3.5, 3.5, 3)